.PHONY: clean All

All:
	@echo "----------Building project:[ ourNotes - Debug ]----------"
	@cd "ourNotes" && "$(MAKE)" -f  "ourNotes.mk"
clean:
	@echo "----------Cleaning project:[ ourNotes - Debug ]----------"
	@cd "ourNotes" && "$(MAKE)" -f  "ourNotes.mk" clean
